<?php
/* @var $block \Magento\Sales\Block\Order\History\Container */

/** @var ProductInfo $productInfoViewModel */
$productInfoViewModel = $block->getData('productInfoViewModel');

$orderId = $block->getOrder()->getId();
$hasAuthenticationPhoto = $productInfoViewModel->hasAuthenticationPhoto($block->getOrder());

?>
<td data-th="<?= $escaper->escapeHtml(__('View Authentication Photo')) ?>" class="col">
    <?php if ($hasAuthenticationPhoto): ?>
        <a href="<?=  $escaper->escapeHtml($productInfoViewModel->getViewProductAuthenticationPhotoUrl($orderId)) ?>"
             class="action view">
            <span><?= $escaper->escapeHtml(__('View Authentication Photo')) ?></span>
        </a>
    <?php endif; ?>
</td>
