<?php
/** @var ProductInfo $productInfoViewModel */
$productInfoViewModel = $block->getData('productInfoViewModel');
$order = $productInfoViewModel->getOrder();
?>
<div class="auth-photo-container">
    <?php

    $orderItems = $order->getAllItems();

    foreach ($orderItems as $index => $item):
        if ($item->getParentItem()):
            continue;
        endif;
        $product =  $item->getProduct();
        $imageUrl = $productInfoViewModel->getProductImage($product); // Helper or method returning image URL
        $authPhoto = $item->getAuthenticationPhoto(); // e.g., from sales_order_item DB
        $authPhotoUrl = $productInfoViewModel->getAuthenticationPhotoUrl($authPhoto);

        ?>
        <div class="product-info-container">
            <div class="product-info">
                <div class="product-image">
                    <img src="<?= $escaper->escapeHtml($imageUrl) ?>" 
                        alt="<?= $escaper->escapeHtml($item->getName()) ?>" />
                </div>
                <div class="product-details">
                    <h2><?= $escaper->escapeHtml($item->getName()) ?></h2>
                    <p>
                        <strong><?= $escaper->escapeHtml('Sku:') ?></strong> &nbsp;
                            <?= /* @noEscape */ $block->prepareSku($item->getSku()) ?>
                    </p>

                    <?php
                    $productOptions = $item->getProductOptions();

                    if (!empty($productOptions)) {
                        if (isset($productOptions['options'])) {
                            foreach ($productOptions['options'] as $option) {
                                echo '<p><strong>' . $escaper->escapeHtml($option['label']) . ':</strong> '
                                        . $escaper->escapeHtml($option['value']) . '</p>';
                            }
                        }

                        if (isset($productOptions['additional_options'])) {
                            foreach ($productOptions['additional_options'] as $option) {
                                echo '<p><strong>' . $escaper->escapeHtml($option['label']) . ':</strong> '
                                        . $escaper->escapeHtml($option['value']) . '</p>';
                            }
                        }

                        if (isset($productOptions['attributes_info'])) {
                            foreach ($productOptions['attributes_info'] as $option) {
                                echo '<p><strong>' . $escaper->escapeHtml($option['label']) . ':</strong> '
                                        . $escaper->escapeHtml($option['value']) . '</p>';
                            }
                        }
                    } ?>

                    <p class="p-price"><strong><?= $escaper->escapeHtml(__('Price:'));?></strong>
                        <?= $escaper->escapeHtml($productInfoViewModel->getFormattedPrice($item->getPrice())); ?>
                    </p>

                    <p>
                        <strong><?= $escaper->escapeHtml(__('Qty:'));?></strong>
                        <ul class="items-qty">
                        <?php if ($item->getQtyOrdered() > 0): ?>
                            <li class="item">
                                <span class="title"><?= $escaper->escapeHtml(__('Ordered')) ?></span>
                                <span class="content">
                                    <?= $escaper->escapeHtml(
                                        $localeFormatter->formatNumber((float) $item->getQtyOrdered())
                                    )?>
                                </span>
                            </li>
                        <?php endif; ?>
                        <?php if ($item->getQtyShipped() > 0): ?>
                            <li class="item">
                                <span class="title"><?= $escaper->escapeHtml(__('Shipped')) ?></span>
                                <span class="content">
                                    <?= $escaper->escapeHtml(
                                        $localeFormatter->formatNumber((float) $item->getQtyShipped())
                                    )?>
                                </span>
                            </li>
                        <?php endif; ?>
                        <?php if ($item->getQtyCanceled() > 0): ?>
                            <li class="item">
                                <span class="title"><?= $escaper->escapeHtml(__('Canceled')) ?></span>
                                <span class="content">
                                    <?= $escaper->escapeHtml(
                                        $localeFormatter->formatNumber((float) $item->getQtyCanceled())
                                    )?>
                                </span>
                            </li>
                        <?php endif; ?>
                        <?php if ($item->getQtyRefunded() > 0): ?>
                            <li class="item">
                                <span class="title"><?= $escaper->escapeHtml(__('Refunded')) ?></span>
                                <span class="content">
                                    <?= $escaper->escapeHtml(
                                        $localeFormatter->formatNumber((float) $item->getQtyRefunded())
                                    )?>
                                </span>
                            </li>
                        <?php endif; ?>
                        </ul>
                    </p>

                    <?php if ($item->getAuthenticationPhoto() !== null): ?>
                        <a href="#" class="modal-trigger" data-modal="auth-modal-<?= $escaper->escapeHtml($index) ?>">
                            <?= $escaper->escapeHtml('View Authentication Photo') ?>
                        </a>
                        <!-- Modal HTML -->
                        <div id="auth-modal-<?= $escaper->escapeHtml($index) ?>" class="auth-modal" 
                                    style="display: none;">
                            <div class="modal-inner-content">
                                <span class="modal-close" 
                                        data-modal="auth-modal-<?= $escaper->escapeHtml($index) ?>">&times;</span>
                                <h2><?= $escaper->escapeHtml('Certificate of Authentication') ?></h2>
                                <img src="<?= $escaper->escapeUrl($authPhotoUrl) ?>" alt="Authentication Photo">
                            </div>
                        </div>


                        
                    <?php endif; ?>
                </div>
            </div>
        </div>

    <?php endforeach; ?>
</div>